### ISSUE TITLE
Data set

### ISSUE THREAD

**Issue by fdujay** [akwasigroch/Pretext-Invariant-Representations#3]
Can you provide the URL of the data set of skin lesion? Thank you!

**Comment by akwasigroch** [comment]
https://challenge.isic-archive.com/landing/2017

**Comment by timothyvanco** [comment]
Hi, I cant find that dataset anymore on that link (website). Please, do you have it somewhere else? :)

**Comment by juliecious** [comment]
[Training.zip](https://isic-challenge-data.s3.amazonaws.com/2017/ISIC-2017_Training_Data.zip)

https://challenge.isic-archive.com/data#2017
